# Generated by Django 3.1.1 on 2021-04-08 14:51

import authentication.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20210408_1741'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', authentication.models.UserManager()),
            ],
        ),
    ]
