# Generated by Django 3.1.1 on 2021-04-08 14:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='plated_end_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 18, 14, 41, 7, 794135, tzinfo=utc)),
        ),
    ]
