# Generated by Django 3.1.1 on 2021-04-08 14:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210408_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='plated_end_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 18, 14, 44, 43, 567176, tzinfo=utc)),
        ),
    ]
