# Generated by Django 3.1.1 on 2021-04-08 14:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20210408_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='plated_end_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 18, 14, 49, 12, 233647, tzinfo=utc)),
        ),
    ]
